version: '3.9'

services:

  bot:
    build: .
    container_name: bot
    environment:
      - BOT_TOKEN=BOT_TOKEN_VALUE  
      - APP_ID=APP_ID_VALUE
      - API_HASH=API_HASH_VALUE 
      - SUDO_USERS=
      - SUPPORT_CHAT_LINK=
      - DOWNLOAD_DIRECTORY=./downloads/
      - G_DRIVE_CLIENT_ID=G_DRIVE_CLIENT_ID_VALUE
      - G_DRIVE_CLIENT_SECRET=G_DRIVE_CLIENT_SECRET_VALUE
      - DATABASE_URL=postgresql://myuser:mypassword@postgres:5432/postgres
    ports:
      - "8080:80"
    depends_on:
      - postgres

  postgres:
    image: postgres 
    container_name: postgres
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=postgres
   # Rest of postgres service config
